// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yebrregwsoxvhvrclcwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllYnJyZWd3c294dmh2cmNsY3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NjI0NjEsImV4cCI6MjA1OTAzODQ2MX0.nViuULtPDi93ayf3JdaoBmGQz71ngHXlBJIKe1lV2DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);